## Task 1

In [1]:
import pandas as pd 
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv("salary.csv")
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
X= df[['YearsExperience']]
y= df['Salary']
model = LinearRegression()
model.fit(X,y)
df['predicted'] = model.predict(X)

## Task 2 Compute residuals

In [12]:
df['residuals'] = y - df['predicted']
df.head()

   Unnamed: 0  YearsExperience   Salary     predicted    residuals
0           0              1.2  39344.0  36188.158752  3155.841248
1           1              1.4  46206.0  38078.151217  8127.848783
2           2              1.6  37732.0  39968.143681 -2236.143681
3           3              2.1  43526.0  44693.124842 -1167.124842
4           4              2.3  39892.0  46583.117306 -6691.117306

When the residual is positive the model underpredicted. When it is negative then the model overpredicted

## Task 3: Compute MAE by Hand

In [15]:
df['abs_residual'] = df['residuals'].abs()
mae = df['abs_residual'].mean()
print(f"On average, the model's salary predictions are off by $ {mae}")

On average, the model's salary predictions are off by $ 4644.2012894435375

## Task 4 Verify with SKlearn

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae_sk = mean_absolute_error(y, df['predicted'])
print(mae_sk)

4644.2012894435375

In [20]:
import numpy as np
# RMSE
RMSE_sk = np.sqrt(mean_squared_error(y, df['predicted']))
print(RMSE_sk)

5592.043608760662

RMSE is larger because it weighs larger errors more.